apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "secrets-manager.fullname" . }}
  labels:
    {{- include "secrets-manager.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "secrets-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "secrets-manager.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "secrets-manager.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if ne .Values.vault.role "" }}
          args:
            - --vault.kubernetes-role={{ .Values.vault.role }}
            - --vault.auth-method=kubernetes
          {{- end }}
          env:
          - name: VAULT_SKIP_VERIFY
            value: "{{ .Values.vault.skip_ssl_verify }}"
          {{- if eq .Values.vault.role "" }}
          - name: VAULT_ROLE_ID
            value: "{{ .Values.vault.role_id }}"
          - name: VAULT_SECRET_ID
            value: "{{ .Values.vault.secret_id }}"
          {{- end }}
          - name: VAULT_ADDR
            value: "{{ .Values.vault.address }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
